# Generated by Django 3.2.12 on 2023-01-09 06:09

import activatedapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vendorapp', '0001_initial'),
        ('customerapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamaraProvider',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('purchase', 'شراء'), ('refund', 'إعادة')], default='purchase', max_length=10, verbose_name='نوع العملية')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='المبلغ')),
                ('currency', models.CharField(max_length=20, verbose_name='العملة')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('capture_id', models.CharField(editable=False, max_length=255, verbose_name='رقم تتبع الدفع')),
                ('order_id', models.CharField(editable=False, max_length=255, verbose_name='رقم معرف الطلب')),
            ],
            options={
                'verbose_name': 'تمارا',
                'verbose_name_plural': 'تمارا',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='TamaraPaymentPageURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح')),
                ('activated_at', models.DateTimeField(null=True, verbose_name='تاريخ التفعيل')),
                ('disabled_at', models.DateTimeField(null=True, verbose_name='تاريخ إلغاء التفعيل')),
                ('amount', models.FloatField(default=0.0, verbose_name='قيمة المبلغ المدفوع')),
                ('order_track_id', models.CharField(editable=False, error_messages={'unique': 'رقم الطلب موجد مسبقاً.'}, max_length=255, unique=True, verbose_name='رقم الطلب')),
                ('checkout_id', models.CharField(editable=False, error_messages={'unique': 'رقم عملية الدفع موجد مسبقاً.'}, max_length=255, unique=True, verbose_name='رقم عملية الدفع')),
                ('checkout_url', models.URLField(verbose_name='رابط عملية الدفع')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamara_payment_page_url', to='customerapp.customer')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tamara_payment_page_url', to='vendorapp.offer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamara_payment_page_url', to='customerapp.order')),
            ],
            options={
                'verbose_name': 'صفحة الدفع لتمارا',
                'verbose_name_plural': 'صفحة الدفع لتمارا',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('activated', activatedapp.models.ActivatedManager()),
                ('archived', activatedapp.models.ArchivedManager()),
            ],
        ),
    ]
