# Generated by Django 3.2.12 on 2023-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_tamarapaymentpageurl_tamaraprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamarapaymentpageurl',
            name='checkout_id',
            field=models.TextField(editable=False, verbose_name='رقم عملية الدفع'),
        ),
        migrations.AlterField(
            model_name='tamarapaymentpageurl',
            name='order_track_id',
            field=models.TextField(editable=False, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='tamaraprovider',
            name='capture_id',
            field=models.TextField(editable=False, verbose_name='رقم تتبع الدفع'),
        ),
        migrations.AlterField(
            model_name='tamaraprovider',
            name='order_id',
            field=models.TextField(editable=False, verbose_name='رقم معرف الطلب'),
        ),
    ]
