# Generated by Django 3.2.12 on 2023-04-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_auto_20230413_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamarapaymentpageurl',
            name='checkout_url',
            field=models.TextField(verbose_name='رابط عملية الدفع'),
        ),
    ]
